# Generated by Django 3.1.7 on 2021-07-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_country_destination_trip_tripdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='image',
            new_name='low_image',
        ),
        migrations.AddField(
            model_name='country',
            name='high_image',
            field=models.URLField(null=True),
        ),
    ]
