# Generated by Django 3.1.7 on 2021-07-07 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20210705_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='destination',
            new_name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
