# Generated by Django 3.1.7 on 2021-07-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20210707_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
