# Generated by Django 3.1.7 on 2021-07-07 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20210707_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='duration',
        ),
        migrations.CreateModel(
            name='TripDetailDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)])),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.destination')),
                ('tripDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.tripdetail')),
            ],
        ),
    ]
