# Generated by Django 3.1.7 on 2021-07-07 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20210707_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='clonedFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tripdetaildestination',
            name='tripDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='planner.tripdetail'),
        ),
        migrations.AlterUniqueTogether(
            name='tripdetaildestination',
            unique_together={('tripDetail', 'destination')},
        ),
    ]
